// Code generated by protoc-gen-ecode v0.1, DO NOT EDIT.
// source: operations.proto

package v1

import (
	"github.com/go-kratos/kratos/pkg/ecode"
)

// to suppressed 'imported but not used warning'
var _ ecode.Codes

// DeploymentErrCode ecode
var (
	NameIsEmptyErr = ecode.New(16409)
)
