// Code generated by protoc-gen-bm v0.1, DO NOT EDIT.
// source: operations.proto

package v1

import (
	"context"

	bm "github.com/go-kratos/kratos/pkg/net/http/blademaster"
	"github.com/go-kratos/kratos/pkg/net/http/blademaster/binding"
)

// to suppressed 'imported but not used warning'
var _ *bm.Context
var _ context.Context
var _ binding.StructValidator

var PathKoOperationsSayHelloURL = "/gstart"

// KoOperationsBMServer is the server API for KoOperations service.
type KoOperationsBMServer interface {
	SayHelloURL(ctx context.Context, req *HelloReq) (resp *HelloResp, err error)
}

var v1KoOperationsSvc KoOperationsBMServer

func koOperationsSayHelloURL(c *bm.Context) {
	p := new(HelloReq)
	if err := c.BindWith(p, binding.Default(c.Request.Method, c.Request.Header.Get("Content-Type"))); err != nil {
		return
	}
	resp, err := v1KoOperationsSvc.SayHelloURL(c, p)
	c.JSON(resp, err)
}

// RegisterKoOperationsBMServer Register the blademaster route
func RegisterKoOperationsBMServer(e *bm.Engine, server KoOperationsBMServer) {
	v1KoOperationsSvc = server
	e.GET("/gstart", koOperationsSayHelloURL)
}
